#pragma once

const float delta_time = 0.02;

#define DRIVETRAIN_STEER_DEADZONE 			0.07
#define DRIVETRAIN_THROTTLE_DEADZONE  		0.03
#define DRIVETRAIN_THROTTLE_MULTIPLIER 		1
#define DRIVETRAIN_STEER_MULTIPLIER 		0.5
#define DRIVETRAIN_THROTTLE_ACCELERATION	5
#define DRIVETRAIN_STEER_ACCELERATION	 	5
